#!name=12306去广告
#!desc=过滤12306应用内广告及开屏广告
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,ad.12306.cn,DIRECT

[Script]
body_rewrite_15 = type=http-response, pattern=^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["materialsList","advertParam"]]]
移除12306应用内广告 = type=http-request, pattern=^https:\/\/mobile\.12306\.cn\/otsmobile\/app\/mgs\/mgw\.htm$, script-path=https://kelee.one/Resource/JavaScript/12306/12306_remove_ads.js

[MITM]
hostname = %APPEND% ad.12306.cn, mobile.12306.cn
