#!name=36氪去广告
#!desc=移除开屏广告、首页右上角运营位、信息流广告、文末广告，移除相关文章推荐、大家都在看及皮肤配置，精简搜索页面、我的页面及底栏。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,adx.36kr.com,REJECT
DOMAIN,ad.jiemian.com,REJECT

[Map Local]
^https:\/\/gateway\.36kr\.com\/api\/mis\/nav\/me\/recom\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gateway\.36kr\.com\/api\/mis\/nav\/search\/hotword\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gateway\.36kr\.com\/api\/mis\/nav\/search\/topicListV2\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gateway\.36kr\.com\/api\/adx\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gateway\.36kr\.com\/api\/mis\/page\/article\/recom\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gateway\.36kr\.com\/api\/mis\/page\/newsflash\/recom\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gateway\.36kr\.com\/api\/mis\/sys\/skin\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_16 = type=http-response, pattern=^https:\/\/gateway\.36kr\.com\/api\/mis\/sys\/config\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.contentConfig","data.positionConfigList","data.switchConfig.ios.sunrise_sign","data.switchConfig.ios.sunrise_sunit_task","data.switchConfig.ios.sunrise_sunit_mall","data.switchConfig.ios.sunrise_distribution_icon","data.secondFloorConfig"]]]
body_rewrite_17 = type=http-response, pattern=^https:\/\/36kr\.com\/global\/sensors\/config\/iOS\.conf\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["configs.disableSDK",true]]]]
body_rewrite_23 = type=http-response, pattern=^https:\/\/gateway\.36kr\.com\/api\/mis\/nav\/home\/subnav\/flow\/, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.adItemList"]]]

[MITM]
hostname = %APPEND% gateway.36kr.com, 36kr.com
