#!name=排班日历去广告
#!desc=移除开屏广告、横幅广告。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/schedule-api\.julanling\.com\/api\d\/get_splash$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/schedule-api\.julanling\.com\/api\d\/index_advert$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/schedule-api\.julanling\.com\/api\d\/queryAdvertConfig$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% schedule-api.julanling.com
