#!name=宝宝树孕育去广告
#!desc=过滤宝宝树孕育广告
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
URL-REGEX,"^http:\/\/go\.babytree\.com\/go_pregnancy\/api\/(index_activity\/get_app_index_activity|sign\/sign_h_5)\?",REJECT-TINYGIF
URL-REGEX,"^http:\/\/go\.babytree\.com\/go_search\/api\/mobile_search_new\/get_multi_search_default_keywords\?",REJECT-TINYGIF
URL-REGEX,"^http:\/\/m\.meitun\.com\/newapi\/router\/topic\/hometptf\/feedRecommend",REJECT-TINYGIF
URL-REGEX,"^http:\/\/pic08\.babytreeimg\.com\/knowledge\/2022\/0923\/\w+",REJECT
URL-REGEX,"^http:\/\/plough\.babytree\.com\/plough\.do",REJECT-TINYGIF

[MITM]
hostname = %APPEND% api.babytree.com, go.babytree.com
