#!name=一刻相册去广告
#!desc=移除开屏广告、横幅广告和弹窗推广。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/pan\.baidu\.com\/act\/api\/conf\?.*conf_key=youa_core_config_ios data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/pan\.baidu\.com\/youai\/material\/v1\/getbynavid\?.*nav_id=1 data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_15 = type=http-response, pattern=^https:\/\/mbd\.baidu\.com\/ccs\/v1\/start\/confsync\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.service.config.advertisement","data.service.config.youa.pm_config_ad"]]]

[MITM]
hostname = %APPEND% pan.baidu.com, mbd.baidu.com
