#!name=百度翻译去广告
#!desc=移除开屏广告、横幅广告，精简我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/fanyi-app\.baidu\.com\/static\/react-activity\/page\/courseBoutique\.html\? - reject

[Map Local]
^https:\/\/fanyi-app\.baidu\.com\/transapp\/v2\/api\/launch\/config\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_14 = type=http-response, pattern=^https:\/\/fanyi-app\.baidu\.com\/transapp\/comment\/my\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.taskBanner","data.act"]]]
body_rewrite_15 = type=http-response, pattern=^https:\/\/fanyi-app\.baidu\.com\/transapp\/recitewd\/myplan\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.activityRec","data.activityRecList"]]]

[MITM]
hostname = %APPEND% fanyi-app.baidu.com
