#!name=贝壳找房去广告
#!desc=移除开屏广告、弹窗广告、悬浮广告、信息流推广、我家页面的装修推荐。移除我的页面的专属推荐、游戏入口、钱包入口。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/apps\.api\.ke\.com\/config\/config\/bootpage\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/apps\.api\.ke\.com\/platform\/shellapp\/userCenter\/feed\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/apps\.api\.ke\.com\/config\/config\/getactivityconfig\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_13 = type=http-response, pattern=^https:\/\/apps\.api\.ke\.com\/platform\/shellapp\/homepage\/initData\/mini\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.bootpage","data.bottom_bar_activity"]]]
body_rewrite_16 = type=http-response, pattern=^https:\/\/apps\.api\.ke\.com\/platform\/shellapp\/userCenter\/info\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.islandModule"]]]

[MITM]
hostname = %APPEND% apps.api.ke.com
