#!name=学习通去广告
#!desc=移除开屏广告、横幅推广，精简校园补给站频道。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/home-yd\.chaoxing\.com\/apis\/data\/getAdsRecommend\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/home-yd\.chaoxing\.com\/apis\/banner\/getConfigInfoForXsqy\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/groupyd2\.chaoxing\.com\/apis\/activity\/getActivitys_attention\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/appswh\.chaoxing\.com\/apis\/activity\/getNoteTopicList\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_13 = type=http-response, pattern=^https:\/\/learn\.chaoxing\.com\/apis\/service\/appConfig\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.ad"]]]
body_rewrite_17 = type=http-response, pattern=^https:\/\/apps\.chaoxing\.com\/apis\/home\/getHpXsqy\.jspx\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.list_timeapp"]]]

[MITM]
hostname = %APPEND% learn.chaoxing.com, home-yd.chaoxing.com, apps.chaoxing.com, groupyd2.chaoxing.com, appswh.chaoxing.com
