#!name=大姨妈月经期助手去广告
#!desc=移除信息流广告，精简首页金刚位及我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/shop18476221\.m\.youzan\.com\/wscshop\/showcase\/feature\? - reject

[Map Local]
^https:\/\/forumapi\.yoloho\.com\/topic\/relate\/recommend\/flow\/getList\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% forumapi.yoloho.com, dataapi.yoloho.com, shop18476221.m.youzan.com
