#!name=豆瓣阅读去广告
#!desc=移除开屏广告、弹窗广告、热门搜索、热搜榜。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/read\.douban\.com\/api\/v2\/ads\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/read\.douban\.com\/api\/v2\/popup$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/read\.douban\.com\/api\/v2\/search\/hot_words$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/read\.douban\.com\/api\/v2\/search\/hot_charts$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/read\.douban\.com\/api\/v2\/search\/rec_urls$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% read.douban.com
