#!name=斗鱼去广告
#!desc=移除开屏、首页视频流、首页轮播图广告，移除直播间悬浮窗。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
URL-REGEX,"^http:\/\/linkmicschedule\.douyucdn\.cn\/im_schedule\/im_gate_list",REJECT
AND,((DEST-PORT,18000),(PROTOCOL,STUN)),REJECT
DOMAIN,stun1.douyucdn.cn,REJECT
DOMAIN,stun1.qvb.qcloud.com,REJECT

[URL Rewrite]
^(http:\/\/)((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\/(hlsh5p1\.douyucdn2\.cn)(.*) $1$5$6 307

[MITM]
hostname = %APPEND% rtbapi.douyucdn.cn, apiv2.douyucdn.cn, venus.douyucdn.cn
