#!name=华尔街见闻去广告
#!desc=移除开屏广告、文末广告、信息流广告，精简底栏。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/advertising\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/kvconfig\/items\/search_keywords_wscnvip$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/search\/hotsearch\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/articles\/hot\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/wallstreetcn\.com\/app-faas\/coupon\/user\/search\/popup$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/lives\/relateddata\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/articles\/relateddata\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/carousel\/information-flow\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_22 = type=http-response, pattern=^https:\/\/api-one-wscn\.awtmt\.com\/apiv1\/content\/articles\/, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.recommend_vip_img_uri"]]]
body_rewrite_23 = type=http-response, pattern=^https:\/\/api-one-wscn\.awtmt\.com\/\/apiv1\/kvconfig\/items\/membersrights$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.vip_article"]]]

[MITM]
hostname = %APPEND% api-one-wscn.awtmt.com
