#!name=华住会去广告
#!desc=移除弹窗、横幅，精简首页。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/hweb-manager\.huazhu\.com\/notice\/getAppPopupNotifyAlert$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hweb-hotel\.huazhu\.com\/home\/getHomeLoinBanner$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hweb-hotel\.huazhu\.com\/\/home\/querySelectHotel$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hweb-hotel\.huazhu\.com\/home\/queryHotelBrand$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hweb-manager\.huazhu\.com\/hotels\/ad\/getHotelListNoticeMerge$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% hweb-manager.huazhu.com, hweb-hotel.huazhu.com, res-pub.huazhu.com
