#!name=喜马拉雅去广告
#!desc=移除开屏广告、播放器广告、各类推荐内容，精简频道和我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,adse.ximalaya.com,REJECT
DOMAIN,adsehera.ximalaya.com,REJECT
DOMAIN,adse.wsa.ximalaya.com,REJECT
DOMAIN,adbehavior.ximalaya.com,REJECT
DOMAIN,adbehavior.wsa.ximalaya.com,REJECT

[MITM]
hostname = %APPEND% gslbali.ximalaya.com, search.ximalaya.com, searchwsa.ximalaya.com, mobile.ximalaya.com, mobilehera.ximalaya.com, mobwsa.ximalaya.com, m.ximalaya.com, mwsa.ximalaya.com
