#!name=得间小说去广告
#!desc=移除开屏广告、章末广告，移除扉页广告提示、听书界面广告提示、搜索栏填充词。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,smad.ms.zhangyue.net,REJECT
DOMAIN,saad.ms.zhangyue.net,REJECT

[Map Local]
^https:\/\/dj\.palmestore\.com\/djad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/dj\.palmestore\.com\/zybk\/api\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/dj\.palmestore\.com\/zyapi\/bookstore\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/dj\.palmestore\.com\/zybk\/api\/bookshelf\/index\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_16 = type=http-response, pattern=^https:\/\/dj\.palmestore\.com\/zybk\/api\/powerup\/userGroup\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["body.sevenDaysAd","body.shortPlayShow","body.sdkShortPlayAB"]]]
body_rewrite_20 = type=http-response, pattern=^https:\/\/dj\.palmestore\.com\/zybk\/api\/search\/index\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["body.keywords"]]]

[MITM]
hostname = %APPEND% dj.palmestore.com
