#!name=京东去广告
#!desc=移除京东开屏广告，精简我的页面产品推广。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
URL-REGEX,"^http:\/\/\w{32}\.jddebug\.com\/diagnose\?",REJECT

[Map Local]
^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(searchBoxWord|stationPullService|uniformRecommend[06]) data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_16 = type=http-response, pattern=^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=basicConfig, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["data.JDMessage.socketmonitor.isSocketEstablishedAhead",0],["data.JDMessage.socketmonitor.isSocketReport",0],["data.JDHttpToolKit.httpdns.httpdns",0]]]]
移除京东广告 = type=http-response, pattern=^https:\/\/api\.m\.jd\.com\/client\.action\?functionId=(deliverLayer|getTabHomeInfo|myOrderInfo|orderTrackBusiness|personinfoBusiness|start|welcomeHome), script-path=https://kelee.one/Resource/JavaScript/JD/JD_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% api.m.jd.com
