#!name=京东外卖去广告
#!desc=移除首页推广、点评页面非美食内容、购物车及我的页面推荐、搜索发现、搜索榜单，精简我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/color\.jddj\.com\/client\.action\?functionId=uniformRecommend data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/color\.jddj\.com\/client\.action\?functionId=search_recommendRanking$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_16 = type=http-response, pattern=^https:\/\/api\.m\.jd\.com\/client\.action$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.searchDTO.searchWords","data.wishlistDTO.bubbleTip"]]]

[MITM]
hostname = %APPEND% color.jddj.com, api.m.jd.com
