#!name=芒果TV去广告
#!desc=移除开屏广告、信息流广告、播放页广告，精简我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,credits.bz.mgtv.com,REJECT
DOMAIN,credits2.bz.mgtv.com,REJECT
DOMAIN,credits3.bz.mgtv.com,REJECT
DOMAIN,dflow.bz.mgtv.com,REJECT
DOMAIN,encounter.bz.mgtv.com,REJECT
DOMAIN,floor.bz.mgtv.com,REJECT
DOMAIN,layer.bz.mgtv.com,REJECT
DOMAIN,mob.bz.mgtv.com,REJECT
DOMAIN,rc-topic-api.bz.mgtv.com,REJECT
DOMAIN,rprain.bz.mgtv.com,REJECT
DOMAIN,rprain.log.mgtv.com,REJECT
DOMAIN,vip.bz.mgtv.com,REJECT
DOMAIN-SUFFIX,da.mgtv.com,REJECT

[MITM]
hostname = %APPEND% dc?.bz.mgtv.com, mobileso.bz.mgtv.com, damang.api.mgtv.com, hb-boom.api.mgtv.com, mobile.api.mgtv.com, mobile.api.hunantv.com, me.bz.mgtv.com, mobile-thor.api.mgtv.com
