#!name=马克水印相机去广告
#!desc=移除开屏广告，拍摄首页悬浮挂件，侧边栏横幅广告。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/marki\.markiapp\.com\/mkg\/MomStats\/getFlowWindowList$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/marki\.markiapp\.com\/mkg\/Advertising\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/marki\.markiapp\.com\/mkg\/MomStats\/getIntegralAdv$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/market-callback\.markiapp\.com\/adcenter\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% marki.markiapp.com, market-callback.markiapp.com
