#!name=每日赛车去广告
#!desc=移除开屏广告、信息流广告。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Script]
body_rewrite_13 = type=http-response, pattern=^https:\/\/api\.romielf\.com\/index\/indexv\d\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["data.advertisement",[]],["data.listadvertising",[]]]]]

[MITM]
hostname = %APPEND% api.romielf.com
