#!name=米游社去广告
#!desc=移除开屏广告、搜索栏热搜及资讯、青少年模式弹窗。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/bbs-api(-ab)?\.miyoushe\.com\/apihub\/api\/getAppSplash$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/bbs-api(-ab)?\.miyoushe\.com\/apihub\/api\/getHotKeywordAndEvent$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/bbs-api-static\.miyoushe\.com\/search\/api\/search\/pre_keyword\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_14 = type=http-response, pattern=^https:\/\/bbs-api(-ab)?\.miyoushe\.com\/apihub\/api\/getAppStartupData$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.resp_map./teenager/api/info","data.resp_map[\"/apihub/api/getAppConfig\"].data.get_app_config_response.config.is_show_teenager_mode_btn","data.resp_map[\"/apihub/api/getAppConfig\"].data.get_app_config_response.config.teenager_popup_freq_type"]]]
body_rewrite_15 = type=http-response, pattern=^https:\/\/bbs-api(-ab)?\.miyoushe\.com\/apihub\/api\/getAppConfig$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["data.config.teenager_popup_freq_type",0],["data.config.is_show_teenager_mode_btn",0]]]]
body_rewrite_16 = type=http-response, pattern=^https:\/\/bbs-api-ab\.miyoushe\.com\/teenager\/api\/info$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["data.is_enabled",false],["data.is_teenager",false],["data.is_force",false]]]]

[MITM]
hostname = %APPEND% bbs-api.miyoushe.com, bbs-api-ab.miyoushe.com
