#!name=OKOK去广告
#!desc=移除开屏广告、横幅广告，精简首页，拦截优惠购页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/shop171777386\.m\.youzan\.com\/v2\/showcase\/homepage\? - reject

[Map Local]
^https:\/\/api\.chips-cloud\.com\/v\d\/home\/collection\/smartv\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.chips-cloud\.com\/v\d\/communityManage\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.chips-cloud\.com\/v\d\/good\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% api.chips-cloud.com, shop171777386.m.youzan.com
