#!name=亲宝宝去广告
#!desc=移除开屏广告、弹窗广告、广告下发、用户行为上报，精简搜索页、育儿页和我的页面，拦截商城页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,apimall.qbb6.com,REJECT

[Script]
精简我的页面 = type=http-response, pattern=^https:\/\/api\.qbb6\.com\/commons\/self\/button\/group\/get\/v\d\?, script-path=https://kelee.one/Resource/JavaScript/Qbb/my.js, requires-body=true
精简育儿页面 = type=http-response, pattern=^https:\/\/apipt\.qbb6\.com\/parenting\/pt\/homepage\/get\/v\d\?, script-path=https://kelee.one/Resource/JavaScript/Qbb/homepage.js, requires-body=true

[MITM]
hostname = %APPEND% api.qbb6.com, apicommunity.qbb6.com, apipt.qbb6.com, apiuser.qbb6.com, apimall.qbb6.com
