#!name=Roborock去广告
#!desc=移除横幅、活动推广、机器人图标，精简服务中心。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/cniot\.roborock\.com\/api\/v1\/app\/theme\/device\/icon\? - reject

[Map Local]
^https:\/\/cniot\.roborock\.com\/api\/v1\/activity\/banner\/list$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/cniot\.roborock\.com\/api\/v1\/activity\/latest$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% cniot.roborock.com, api.roborock.com
