#!name=Sofascore去广告
#!desc=移除横幅及信息流广告
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/api\.sofascore\.com\/api\/v\d\/dsp\/country\/[A-Z]{2}$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.sofascore\.com\/api\/v\d\/trending\/grid\/tiles\/[A-Z]{2}$ data-type=text data="{"tiles":[]}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% api.sofascore.com
