#!name=Soul去广告
#!desc=移除开屏广告、移除话题页面热Soul话题、移除评论区礼物榜、移除更新提示、移除青少年弹窗、移除我的页面推广、移除悬浮部件。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,soulapp.cn,DIRECT
IP-CIDR,8.210.3.170/32,DIRECT,no-resolve
IP-CIDR,47.75.72.47/32,DIRECT,no-resolve
DOMAIN,ad-h5-cdn.soulapp.cn,REJECT
DOMAIN,ad-h5-station-cdn.soulapp.cn,REJECT
DOMAIN,ad-r.soulapp.cn,REJECT
DOMAIN,soul-ad.soulapp.cn,REJECT
IP-CIDR,47.56.131.76/32,REJECT,no-resolve
IP-CIDR,47.97.215.55/32,REJECT,no-resolve
IP-CIDR,47.99.42.29/32,REJECT,no-resolve
IP-CIDR,47.110.187.87/32,REJECT,no-resolve
IP-CIDR,47.243.147.125/32,REJECT,no-resolve
IP-CIDR,120.27.235.201/32,REJECT,no-resolve
IP-CIDR,121.196.197.147/32,REJECT,no-resolve

[MITM]
hostname = %APPEND% api*.soulapp.cn, gateway-mobile-gray.soulapp.cn, post.soulapp.cn, ssp.soulapp.cn
