#!name=智慧苏州去广告
#!desc=移除开屏广告、横幅，移除信息流推广。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https?:\/\/newapp2\.szsmk\.com\/app\/config\/queryMainAd data-type=text data="{"message":"操作成功","main_ad_list":[],"code":"000000"}" header="Content-Type:application/json"
^https?:\/\/newapp2\.szsmk\.com\/app\/config\/(queryCarousel|queryRecommendation)\/ data-type=text data="{"code":"000000","message":"操作成功","list":[]}" header="Content-Type:application/json"

[MITM]
hostname = %APPEND% newapp2.szsmk.com
