#!name=他趣去广告
#!desc=移除各类弹窗、横幅，精简我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/gw-cn\.jiaoliuqu\.com\/taqu-homepage\/v\d\/Banner\/getBannerByPositions\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/bbs\/v5\/Guide\/photoGuide\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/i\/v\d\/homepage\/completeGuideV\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/i\/v\d\/asset\/toast\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/bbs\/v5\/Sign\/getDailySigninInfoV4\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/taqu-hichat\/v\d\/Hichat\/getRecommendInfo\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/live_api\/v\d\/Banner\/getBannerListV\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/live_api\/v\d\/HallScroll\/getList\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/gw-cn\.jiaoliuqu\.com\/taqu-msg-guide\/v\d\/RecommendColumn\/getList\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% gw-cn.jiaoliuqu.com
