#!name=多屏互动去广告
#!desc=移除开屏广告、横幅推广、搜索填充词，移除广告下发。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/tcast-o\.api\.leiniao\.com\/tcast\/ads\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/tcast-o\.api\.leiniao\.com\/tcast\/v\d\/selection\/banner$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/tcast-o\.api\.leiniao\.com\/tcast\/v\d\/searchrank$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/tcast-o\.api\.leiniao\.com\/tcast\/v\d\/selection\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/tcast-o\.api\.leiniao\.com\/tcast\/message\/v\d\/activity\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% tcast-o.api.leiniao.com
