#!name=TubeMax去广告
#!desc=过滤TubeMax广告
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN-SUFFIX,adjust.com,REJECT
DOMAIN-SUFFIX,applvn.com,REJECT
DOMAIN-SUFFIX,app-measurement.com,REJECT
DOMAIN-SUFFIX,pangle.io,REJECT
DOMAIN-SUFFIX,applovin.com,REJECT
DOMAIN-SUFFIX,appier.net,REJECT
DOMAIN-SUFFIX,adsmoloco.com,REJECT
DOMAIN-SUFFIX,adcanvas.com,REJECT

[MITM]
hostname = %APPEND% *.i18n-pglstatp.com
