#!name=WakeUp课程表去广告
#!desc=移除横幅广告、弹窗广告，精简我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/api\.wakeup\.fun\/wakeup\/app\/bannerconf$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_14 = type=http-response, pattern=^https:\/\/api\.wakeup\.fun\/wakeup\/user\/mine$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.bannerItems"]]]

[MITM]
hostname = %APPEND% api.wakeup.fun
