#!name=易校园去广告
#!desc=移除开屏广告、横幅广告、弹窗广告、悬浮广告、文末广告、消息广告、校园头条，精简首页金刚位和我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/compus\.xiaofubao\.com\/compus\/advertising\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_14 = type=http-response, pattern=^https:\/\/compus\.xiaofubao\.com\/compus\/user\/getUserExt$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.adPopSwitch","data.adSplashSwitch"]]]

[MITM]
hostname = %APPEND% compus.xiaofubao.com
