#!name=好轻去广告
#!desc=移除开屏广告、弹窗广告、横幅推广、商品推广，精简我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/yunmai\.sfo-tx-beijing-02\.saas\.sensorsdata\.cn\/api\/v2\/sfo\/user_popup_configs\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/restapi\.iyunmai\.com\/ad-api\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/apisvr\.iyunmai\.com\/api\/ios\/first-page-module\/center_menu\.json\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/restapi\.iyunmai\.com\/api\/ios\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% yunmai.sfo-tx-beijing-02.saas.sensorsdata.cn, apisvr.iyunmai.com, restapi.iyunmai.com
