#!name=阿里云盘
#!desc=过滤阿里云盘广告
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
IP-CIDR,203.107.1.1/24,REJECT,no-resolve

[Map Local]
^https:\/\/member\.alipan\.com\/v2\/activity\/sign_in_luckyBottle data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.alipan\.com\/adrive\/v1\/file\/getTopFolders data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]

[阿里云盘]移除广告 = type=http-response, pattern=^https:\/\/(biz)?api\.alipan\.com\/apps\/v\d\/users?\/home\/(?:news|widgets), script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Alipan/Alipan.js, requires-body=true

[阿里云盘]移除广告 = type=http-response, pattern=^https:\/\/member\.alipan\.com\/v1\/users\/onboard_list, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/Alipan/Alipan.js, requires-body=true

[MITM]
hostname = %APPEND% *api.alipan.com, *api.aliyundrive.com, member.alipan.com, member.aliyundrive.com
