#!name=BoxJs
#!desc=Data manager，使用前请在本插件的详情页面为[PROXY]项分配代理策略。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]
BoxJs = type=http-request, pattern=^https?:\/\/(.+\.)?boxjs\.(com|net), script-path=https://raw.githubusercontent.com/chavyleung/scripts/master/box/chavy.boxjs.js, requires-body=true, timeout=120

[MITM]
hostname = %APPEND% boxjs.com, boxjs.net, *.boxjs.com, *.boxjs.net
