#!name=CC直播去广告
#!desc=移除信息流推广和横幅，精简顶部标签。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/cc\.163\.com\/act\/m\/daily\/ad_ - reject

[Map Local]
^http:\/\/mshare\.cc\.163\.com\/mshare\/startadv_mobile_v\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/appapi\.cc\.163\.com\/v\d\/mixfloatingwindow\/floating_windows\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^http:\/\/api\.cc\.163\.com\/v1\/mpopuprecommend\/exit_room_conf$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% api.cc.163.com, cc.163.com, mshare.cc.163.com, appapi.cc.163.com
