#!name=触站去广告
#!desc=移除开屏广告、弹窗广告、各页面横幅推广，移除首页悬浮挂件。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/app\.huashi6\.com\/app\/index\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/app\.huashi6\.com\/app\/works\/relative$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/app\.huashi6\.com\/app\/index\/follow\/all_random\/list$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/app\.huashi6\.com\/app\/index\/csyxh\/icon$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_14 = type=http-response, pattern=^https:\/\/app\.huashi6\.com\/app\/common\/config$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["data.disableAd",true],["data.showTopFloatAdvanceTips",false]]],["json-del",["data.adsConfigIOS","data.adsConfigAndroid","data.url.tabMarket"]]]

[MITM]
hostname = %APPEND% app.huashi6.com
