#!name=彩云天气Pro
#!desc=过滤彩云天气广告，解锁SVIP功能。\n解锁功能需App版本低于7.20.2。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,abyss.cyapi.cn,REJECT
DOMAIN,ad.cyapi.cn,REJECT
DOMAIN,gather.colorfulclouds.net,REJECT

[Map Local]
^https?:\/\/api\.caiyunapp\.com\/v1\/activity data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/biz\.cyapi\.cn\/(p\/v1\/entries|p\/v1\/trial_card\/info|v2\/product) data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/starplucker\.cyapi\.cn\/v3\/(config\/cypage\/\w+\/conditions|notification\/message_center|operation\/homefeatures) data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/wrapper\.cyapi\.cn\/v1\/activity\? data-type=file data="https://raw.githubusercontent.com/Keywos/rule/main/mocks/caiyun.json" status-code=200 header="Content-Type:application/json"

[Script]

[彩云天气]共享会员 = type=http-request, pattern=^https:\/\/wrapper\.cyapi\.cn\/v1\/(nafp\/origin_images|satellite)\?, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/ColorfulCloudsWeatherPro/ColorfulCloudsWeatherPro.js

[彩云天气]共享会员 = type=http-response, pattern=^https:\/\/biz\.cyapi\.cn\/(api\/v1\/user_detail|p\/v1\/vip_info|v2\/user), script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/ColorfulCloudsWeatherPro/ColorfulCloudsWeatherPro.js, requires-body=true

[彩云天气]移除广告 = type=http-response, pattern=^https:\/\/(wrapper\.cyapi\.cn|api\.caiyunapp\.com|cdn-w\.caiyunapp\.com)\/v1\/activity\?, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/ColorfulCloudsWeatherPro/ColorfulCloudsWeatherPro.js, requires-body=true

[MITM]
hostname = %APPEND% biz.cyapi.cn, starplucker.cyapi.cn, api.caiyunapp.com, cdn-w.caiyunapp.com, wrapper.cyapi.cn
