#!name=Cookie & Task
#!desc=自动完成每日签到任务，按需开启相应功能即可。\n具体使用方法请查看所引用脚本或插件内详细说明。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]

[微信支付有优惠]领金币Token = type=http-response, pattern=https:\/\/payapp\.weixin\.qq\.com\/(coupon-center-user\/home\/login|coupon-center-award\/award\/detail), script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/wechat_pay_coupon.js, requires-body=true

[微信支付有优惠]领金币Task = type=cron, cronexp={{{Cron-wechatpay}}}, script-path=https://raw.githubusercontent.com/FoKit/Scripts/main/scripts/wechat_pay_coupon.js

[阿里云盘]每日签到Token = type=http-request, pattern=^https:\/\/(auth|aliyundrive)\.alipan\.com\/v2\/account\/token, script-path=https://gist.githubusercontent.com/Sliverkiss/33800a98dcd029ba09f8b6fc6f0f5162/raw/aliyun.js, requires-body=true

[阿里云盘]每日签到Task = type=cron, cronexp={{{Cron-alipan}}}, script-path=https://gist.githubusercontent.com/Sliverkiss/33800a98dcd029ba09f8b6fc6f0f5162/raw/aliyun.js

[微博]每日签到Token = type=http-request, pattern=^https?:\/\/api\.weibo\.cn\/\d\/users\/show, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/CookieTask/WeiboCookieTask.js

[微博]每日签到Task = type=cron, cronexp={{{Cron-weibo}}}, script-path=https://raw.githubusercontent.com/sooyaaabo/Loon/main/Script/CookieTask/WeiboCookieTask.js

[哔哩哔哩App]每日等级任务Token = type=http-request, pattern=^https?:\/\/app\.bilibili\.com\/x\/resource\/fingerprint\?, script-path=https://raw.githubusercontent.com/ClydeTime/BiliBili/main/js/BiliBiliDailyBonus.js

[哔哩哔哩]每日等级任务Task = type=cron, cronexp={{{Cron-bilibili}}}, script-path=https://raw.githubusercontent.com/ClydeTime/BiliBili/main/js/BiliBiliDailyBonus.js

[MITM]
hostname = %APPEND% payapp.weixin.qq.com, auth.alipan.com, auth.aliyundrive.com, api.weibo.cn, cm.bilibili.com, m.bilibili.com
