#!name=酷安
#!desc=过滤酷安广告
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/api\.coolapk\.com\/v6\/search\?.*type=hotSearch data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]

[酷安]移除广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/main\/init, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

[酷安]移除广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/main\/indexV8, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

[酷安]移除广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/page\/dataList, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

[酷安]移除广告 = type=http-response, pattern=^https:\/\/api\.coolapk\.com\/v6\/account\/loadConfig\?key=my_page_card_config, script-path=https://raw.githubusercontent.com/ZenmoFeiShi/Qx/main/KuAn.js, requires-body=true

[MITM]
hostname = %APPEND% api.coolapk.com
