#!name=Dlabel云标签去广告
#!desc=移除开屏广告及首页横幅。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/dlabel\.ctaiot\.com\/api\/spreadstart\/list\.json\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/dlabel\.ctaiot\.com\/api\/spread\/journey\/select\.json\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% dlabel.ctaiot.com
