#!name=粉笔去广告
#!desc=移除开屏广告、弹窗广告、悬浮广告、热门搜索，移除底栏皮肤，精简我的页面。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/keapi\.fenbi\.com\/app\/iphone\/position_resource\/get_banners\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/market-api\.fenbi\.com\/iphone\/v1\/assistant\/info\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/keapi\.fenbi\.com\/app\/iphone\/position_resource\/get_home_banners\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/ke\.fenbi\.com\/iphone\/v3\/timetable\/today_with_public_episodes\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hera-webapp\.fenbi\.com\/iphone\/topic\/hotquery\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hera-webapp\.fenbi\.com\/iphone\/announcement\/hotquery\/list\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_19 = type=http-response, pattern=^https:\/\/ke\.fenbi\.com\/iphone\/v3\/apps\/config\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.bottomIconInfos.position.iconDefaultUrl","data.bottomIconInfos.position.iconSelectedUrl","data.bottomIconInfos.position.nightModeIconDefaultUrl","data.bottomIconInfos.position.nightModeIconSelectedUrl"]]]

[MITM]
hostname = %APPEND% keapi.fenbi.com, market-api.fenbi.com, ke.fenbi.com, hera-webapp.fenbi.com
