#!name=爱奇艺
#!desc=悦享品质 [悦享广告]
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
IP-CIDR,103.44.59.54/32,REJECT,no-resolve
IP-CIDR,111.63.147.158/32,REJECT,no-resolve
IP-CIDR,116.211.198.237/32,REJECT,no-resolve
DOMAIN-SUFFIX,cupid.iqiyi.com,DIRECT
DOMAIN,api.iqiyi.com,REJECT
DOMAIN,access.if.iqiyi.com,REJECT

[Map Local]
^https?:\/\/iface2\.iqiyi\.com\/control\/3\.0\/init_proxy\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/act\.vip\.iqiyi\.com\/interact\/api\/v2\/show\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/iface2\.iqiyi\.com\/ivos\/interact\/video\/data\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/iface2\.iqiyi\.com\/video\/3\.0\/v_interface_proxy\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/iface2\.iqiyi\.com\/views_pop\/3\.0\/pop_control\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_27 = type=http-response, pattern=^https:\/\/cards\.iqiyi\.com\/views_home\/3\.0\/qy_home\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["base.statistics"]]]
body_rewrite_57 = type=http-response, pattern=^https?:\/\/iface2\.iqiyi\.com\/views_menus\/3\.0\/bottom_theme\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["theme_list"]]]
body_rewrite_62 = type=http-response, pattern=^https?:\/\/iface2\.iqiyi\.com\/fusion\/3\.0\/common_switch\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["content.resource.cast_device_ad"]],["json-replace",[["content.switchs.app_ad.app_ad_enable",0],["content.switchs.app_ad.app_ad_duration",0],["content.switchs.ios_tech.kPreadAdHintSwitch",0],["content.switchs.ios_tech.ad_download",0],["content.switchs.m_qiyi_ios_tech.KFocusAdVideoPlayTimesIn4G",0]]]]
body_rewrite_65 = type=http-response, pattern=^https?:\/\/(kjp|t7z)\.cupid\.iqiyi\.com\/mixer\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["adSlots"]]]
body_rewrite_67 = type=http-response, pattern=^https?:\/\/search\.video\.iqiyi\.com\/q\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data"]]]

[MITM]
hostname = %APPEND% -i.vip.iqiyi.com, *.iqiyi.com
