#!name=掌阅去广告
#!desc=移除开屏广告、悬浮广告、弹窗广告、朗读音色广告及我的页面广告，移除各页面的横幅轮播图。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,saad.ms.zhangyue.net,REJECT

[Map Local]
^https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/zyapi\/bookstore\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/bookstore\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/zybk\/api\/pop\/index\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/zyapi\/bookstore\/user\/mytab\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/zyboot\/activity\/mytab\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/zyam\/app\/app\.php\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_17 = type=http-response, pattern=^https:\/\/(webboot\.zhangyue\.com|ih2\.ireader\.com)\/zybook4\/iphone\/u\/p\/api\.php\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["Splash"]]]

[MITM]
hostname = %APPEND% webboot.zhangyue.com, ih2.ireader.com
