#!name=iRingo:WeatherKit
#!desc=1.解锁全部天气功能；2.替换空气质量数据；3.添加下一小时降水数据；4.添加天气数据。\n仅支持iOS 18 & macOS 15 & watchOS 11及以上版本。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,weather-analytics-events.apple.com,REJECT-DROP
DOMAIN-SUFFIX,tthr.apple.com,REJECT-DROP
DOMAIN,tether.edge.apple,REJECT-DROP

[Script]

[iRingo_WeatherKit]v1.availability.response = type=http-response, pattern=^https?:\/\/weatherkit\.apple\.com\/api\/v1\/availability\/, script-path=https://github.com/NSRingo/WeatherKit/releases/latest/download/response.bundle.js, requires-body=true, argument="[{{{DataSets}}},{{{Weather.Provider}}},{{{NextHour.Provider}}},{{{AQI.Provider}}},{{{AQI.ReplaceProviders}}},{{{AQI.ComparisonProvider}}},{{{AQI.Local.ReplaceScales}}},{{{AQI.Local.Scale}}},{{{AQI.Local.ConvertUnits}}},{{{API.ColorfulClouds.Token}}},{{{API.QWeather.Host}}},{{{API.QWeather.Token}}},{{{API.WAQI.Token}}},{{{LogLevel}}}]"

[iRingo_WeatherKit]v1.weather.request = type=http-request, pattern=^https?:\/\/weatherkit\.apple\.com\/api\/v2\/weather\/, script-path=https://github.com/NSRingo/WeatherKit/releases/latest/download/request.bundle.js, argument="[{{{DataSets}}},{{{Weather.Provider}}},{{{NextHour.Provider}}},{{{AQI.Provider}}},{{{AQI.ReplaceProviders}}},{{{AQI.ComparisonProvider}}},{{{AQI.Local.ReplaceScales}}},{{{AQI.Local.Scale}}},{{{AQI.Local.ConvertUnits}}},{{{API.ColorfulClouds.Token}}},{{{API.QWeather.Host}}},{{{API.QWeather.Token}}},{{{API.WAQI.Token}}},{{{LogLevel}}}]"

[iRingo_WeatherKit]v2.weather.response = type=http-response, pattern=^https?:\/\/weatherkit\.apple\.com\/api\/v2\/weather\/, script-path=https://github.com/NSRingo/WeatherKit/releases/latest/download/response.bundle.js, requires-body=true, binary-body-mode=true, argument="[{{{DataSets}}},{{{Weather.Provider}}},{{{NextHour.Provider}}},{{{AQI.Provider}}},{{{AQI.ReplaceProviders}}},{{{AQI.ComparisonProvider}}},{{{AQI.Local.ReplaceScales}}},{{{AQI.Local.Scale}}},{{{AQI.Local.ConvertUnits}}},{{{API.ColorfulClouds.Token}}},{{{API.QWeather.Host}}},{{{API.QWeather.Token}}},{{{API.WAQI.Token}}},{{{LogLevel}}}]"

[MITM]
hostname = %APPEND% weatherkit.apple.com
