#!name=iTunes
#!desc=iTunes系列解锁合集，在设置中选择需要使用的原作者脚本以使用此插件。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]

[iTunes]解锁会员系列 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://raw.githubusercontent.com/chxm1023/Rewrite/main/iTunes.js, requires-body=true

[iTunes]解锁会员系列 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://gist.githubusercontent.com/ddgksf2013/9e0f6c7341beea09a31aa309d9d7f502/raw/buyitunes.js, requires-body=true

[iTunes]解锁会员系列 = type=http-response, pattern=^https?:\/\/buy\.itunes\.apple\.com\/verifyReceipt$, script-path=https://raw.githubusercontent.com/Guding88/Script/main/APPheji_iTunes.js, requires-body=true

[MITM]
hostname = %APPEND% buy.itunes.apple.com
