#!name=酷我音乐
#!desc=过滤酷我音乐广告，解锁会员功能。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
URL-REGEX,"^http:\/\/rich\.kuwo\.cn\/AdService\/",REJECT-TINYGIF
URL-REGEX,"^http:\/\/wapi\.kuwo\.cn\/openapi\/v\d\/user\/freeMode\/",REJECT-TINYGIF
URL-REGEX,"^http:\/\/wapi\.kuwo\.cn\/openapi\/v\d\/app\/pasterAdvert\/",REJECT-TINYGIF
URL-REGEX,"^http:\/\/wapi\.kuwo\.cn\/openapi\/v\d\/app\/startup\/config",REJECT-TINYGIF
URL-REGEX,"^http:\/\/rich\.kuwo\.cn\/EcomResourceServer\/",REJECT-TINYGIF
IP-CIDR,111.206.98.63/32,REJECT,no-resolve
URL-REGEX,"^http:\/\/searchrecterm\.kuwo\.cn\/recterm\.s",REJECT-TINYGIF
URL-REGEX,"^http:\/\/wapi\.kuwo\.cn\/openapi\/v\d\/app\/newMenuList\/menuListInfo",REJECT-TINYGIF
URL-REGEX,"^http:\/\/vip\d\.kuwo\.cn\/vip\/v\d\/sysinfo\?op=getRePayAndDoPayBox",REJECT-TINYGIF
URL-REGEX,"^http:\/\/wapi\.kuwo\.cn\/openapi\/v\d\/album\/adBar\/",REJECT-TINYGIF

[Map Local]
^https:\/\/vip\d\.kuwo\.cn\/commercia\/vipconf\/projectPage\/getPageContent data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/tingshu\.kuwo\.cn\/v2\/api\/pay\/user\/info data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/appi\.kuwo\.cn\/kuwopay\/personal\/cells data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]

[酷我音乐]解锁播放器 = type=http-request, pattern=^https?:\/\/vip1\.kuwo\.cn\/commercia\/vip\/player\/getStyleListByModel, script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/kuwo.js

[酷我音乐]解锁会员 = type=http-response, pattern=^https?:\/\/(?:musicpay|nmobi|vip1|audiobookpay|tingshu|anymatch|mobilebasedata|rich|mobilead|wapi)\.kuwo\.cn\/(?:music\.pay\?newver=\d+|mobi.s\?f=kwxs|vip\/(?:enc\/user\/vip\?op=ui&uid=|v2\/theme\?op=gd)|a\.p|v2\/api\/pay\/user\/info|api\/music\/info|AdService\/kaiping\/adinfo|EcomResourceServer\/(?:adEarnGuajian\/adinfo|getMotor\.do)|openapi\/v1\/(?:operate\/homePage|user\/freeMode\/h5\/text|operate\/message\/info|user\/dolby\/text)|commercia\/(?:vipTab\/myTab\/base|userAssets\/downloadCoupon\/reduce|recall\/pop\/jxhGearInfo|vip\/(?:dressCenter\/getResourceList|player\/getStyleListByModel))|api\/v2\/pay\/app\/getConfigInfo(?:\?configType)?|vip\/v2\/sysinfo|commercia\/recall\/pop\/jxhMultiGearInfo), script-path=https://raw.githubusercontent.com/WeiGiegie/666/main/kuwo.js, requires-body=true, timeout=60

[酷我音乐]移除广告 = type=http-response, pattern=^https?:\/\/(mgxhtj|nmobi|searchrecterm)\.kuwo\.cn\/(mgxh|mobi|recterm)\.s, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/kuwo/kuwo.js, requires-body=true

[酷我音乐]移除广告 = type=http-response, pattern=^https?:\/\/audiobookpay\.kuwo\.cn\/a\.p, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/kuwo/kuwo.js, requires-body=true

[酷我音乐]移除广告 = type=http-response, pattern=^https?:\/\/musicpay\.kuwo\.cn\/music\.pay, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/kuwo/kuwo.js, requires-body=true

[酷我音乐]移除广告 = type=http-response, pattern=^https?:\/\/vip1\.kuwo\.cn\/vip\/(enc\/user\/vip\?op=ui|v\d\/theme\?op=gd), script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/kuwo/kuwo.js, requires-body=true

[酷我音乐]移除广告 = type=http-response, pattern=^https?:\/\/vip1\.kuwo\.cn\/vip\/v\d\/user\/vip\?op=ui, script-path=https://raw.githubusercontent.com/fmz200/wool_scripts/main/Scripts/kuwo/kuwo.js, requires-body=true

[MITM]
hostname = %APPEND% anymatch.kuwo.cn, appi.kuwo.cn, audiobookpay.kuwo.cn, mc.tencentmusic.com, mgxhtj.kuwo.cn, mobilead.kuwo.cn, mobilebasedata.kuwo.cn, musicpay.kuwo.cn, nmobi.kuwo.cn, rich.kuwo.cn, searchrecterm.kuwo.cn, tingshu.kuwo.cn, vip*.kuwo.cn, *.kuwo.cn
