#!name=芒果TV去广告
#!desc=过滤芒果TV客户端广告
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,credits.bz.mgtv.com,REJECT
DOMAIN,credits2.bz.mgtv.com,REJECT
DOMAIN,credits3.bz.mgtv.com,REJECT
DOMAIN,dflow.bz.mgtv.com,REJECT
DOMAIN,encounter.bz.mgtv.com,REJECT
DOMAIN,floor.bz.mgtv.com,REJECT
DOMAIN,layer.bz.mgtv.com,REJECT
DOMAIN,mob.bz.mgtv.com,REJECT
DOMAIN,rc-topic-api.bz.mgtv.com,REJECT
DOMAIN,rprain.bz.mgtv.com,REJECT
DOMAIN,rprain.log.mgtv.com,REJECT
DOMAIN,vip.bz.mgtv.com,REJECT
DOMAIN-SUFFIX,da.mgtv.com,REJECT

[Map Local]
^https:\/\/dc\.bz\.mgtv\.com\/dynamic\/v\d\/skin\/config\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/dc\.bz\.mgtv\.com\/dynamic\/v\d\/channel\/ads\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^http:\/\/mobileso\.bz\.mgtv\.com\/spotlight\/search\/v\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/damang\.api\.mgtv\.com\/station\/album\/red\/dot\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/hb-boom\.api\.mgtv\.com\/release\/pullReleaseInfo$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/mobile\.api\.mgtv\.com\/v\d\/mobile\/checkUpdate\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/mobileso\.bz\.mgtv\.com\/mobile\/recommend\/v\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_33 = type=http-response, pattern=^https?:\/\/mobile\.api\.(mgtv|hunantv)\.com\/mobile\/config\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["data.dc_adConfig",0],["data.XmsellSwitch",0],["data.damang_tab",0],["data.relative_ads",0],["data.second_floor_guide_switch",0],["data.XmVideoB",0],["data.damang_duanju_tab",0]]]]

[MITM]
hostname = %APPEND% dc?.bz.mgtv.com, mobileso.bz.mgtv.com, damang.api.mgtv.com, hb-boom.api.mgtv.com, mobile.api.mgtv.com, mobile.api.hunantv.com, me.bz.mgtv.com, mobile-thor.api.mgtv.com
