#!name=美颜相机去广告
#!desc=移除开屏广告、应用内弹窗，精简首页和我的页面。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,adui.tg.meitu.com,REJECT

[Map Local]
^https:\/\/api\.meiyan\.com\/operation\/home_banner\.json\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.meiyan\.com\/vip\/permission_update_popup\.json\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_17 = type=http-response, pattern=^https:\/\/api\.meiyan\.com\/operation\/get_config\.json\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["response.time_limit","response.bubble","response.person_center"]],["json-replace",[["response.function_pop.meiyan_style.is_pop",false],["response.onoff.vip_half_window_exit_remain_popup.open",0],["response.onoff.vip_home_exit_remain_popup",0]]]]
精简首页功能栏目并移除美颜推荐 = type=http-response, pattern=^https:\/\/api\.meiyan\.com\/operation\/home\.json\?, script-path=https://kelee.one/Resource/JavaScript/MeituMYXJ/MeituMYXJ_remove_ads.js, requires-body=true

[MITM]
hostname = %APPEND% api.meiyan.com
