#!name=NodeSeek
#!desc=NodeSeek每日签到。登录账号进入设置页面以获取Token，成功后关闭Token脚本。\n可在BoxJs中设置是否启用领取随机鸡腿，默认为固定5个鸡腿。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]

[NodeSeek]每日签到Token = type=http-response, pattern=^https:\/\/www\.nodeseek\.com\/api\/account\/getInfo\/.+\?readme=1&signature=1&phone=1, script-path=https://gist.githubusercontent.com/Sliverkiss/2b5acc2c4960dd06618c6912302c2c7f/raw/nodeseek.js, requires-body=true, timeout=60

[NodeSeek]每日签到Task = type=cron, cronexp={{{Cron-nodeseek}}}, script-path=https://gist.githubusercontent.com/Sliverkiss/2b5acc2c4960dd06618c6912302c2c7f/raw/nodeseek.js, timeout=60

[MITM]
hostname = %APPEND% www.nodeseek.com
