#!name=铁路12306
#!desc=过滤铁路12306广告
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,ad.12306.cn,DIRECT

[Script]

[铁路12306]移除开屏广告 = type=http-request, pattern=^https:\/\/ad\.12306\.cn\/ad\/ser\/getAdList$, script-path=https://raw.githubusercontent.com/kokoryh/Sparkle/master/dist/12306.js, requires-body=true

[铁路12306]移除应用内广告 = type=http-response, pattern=^https:\/\/mobile\.12306\.cn\/otsmobile\/app\/mgs\/mgw\.htm$, script-path=https://raw.githubusercontent.com/kokoryh/Sparkle/master/dist/12306.js

[MITM]
hostname = %APPEND% ad.12306.cn, mobile.12306.cn
