#!name=资源预览
#!desc=预览资源
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Header Rewrite]
http-request ^https:\/\/(.*\.)?kelee\.one(\/.*)? header-replace 'User-Agent' 'Surge iOS/5151'
http-response ^https:\/\/(.*\.)?kelee\.one(\/.*)? header-add 'content-disposition' 'inline'
http-response ^https:\/\/(.*\.)?kelee\.one(\/.*)? header-replace 'content-type' 'text/plain; charset=utf-8'

[MITM]
hostname = %APPEND% *.kelee.one, kelee.one
