#!name=资源预览
#!desc=预览资源
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Header Rewrite]
http-request ^https?:\/\/(.*\.)?kelee\.one\/ header-replace User-Agent "Surge iOS/9515"
http-response ^https?:\/\/(.*\.)?kelee\.one\/ header-replace Content-Disposition "inline"
http-response ^https?:\/\/(.*\.)?kelee\.one\/ header-replace Content-Type "text/plain; charset=utf-8"

[MITM]
hostname = %APPEND% *.kelee.one, kelee.one
