#!name=Spotify
#!desc=过滤Spotify广告，修改插件自定义配置项需要重新登陆方可生效。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[URL Rewrite]
^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/artistview\/v1\/artist\/(.*)&platform=iphone https://spclient.wg.spotify.com/artistview/v1/artist/$1&platform=ipad header

[Map Local]
^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/pendragon\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]

[Spotify]Protobuf = type=http-response, pattern=^https:\/\/(?:\w+-spclient|spclient\.wg)\.spotify\.com(?::443)?\/(?:bootstrap|user-customization-service), script-path=https://raw.githubusercontent.com/001ProMax/Surge/main/Script/Spotify.Crack.Dev.js, requires-body=true, binary-body-mode=true, timeout=5, argument="[{{{tab}}},{{{useractivity}}}]"

[MITM]
hostname = %APPEND% *-spclient.spotify.com, spclient.wg.spotify.com
