#!name=TestFlight
#!desc=解除TestFlight区域限制，以解决安装或更新TestFlight内App时, 提示“APP不可用”问题。\niOS/iPadOS/tvOS 26已禁止TestFlight MitM，请禁用此插件。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[General]
skip-proxy = %APPEND% iosapps.itunes.apple.com

[Script]
body_rewrite_19 = type=http-request, pattern=^https?:\/\/testflight\.apple\.com\/v\d\/accounts\/.+?\/install$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["replace-regex",[["\"storefrontId\" : \"\\d{6}-\\d{2},\\d{2}\",","\"storefrontId\":\"143441-19,29\","]]]]

[MITM]
hostname = %APPEND% testflight.apple.com
