#!name=TestFlight地区解锁
#!desc=解除TestFlight的区域限制，支持tvOS。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]
body_rewrite_15 = type=http-request, pattern=^https?:\/\/testflight\.apple\.com\/v\d\/accounts\/.+?\/install$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["replace-regex",[["\"storefrontId\" : \"\\d{6}-\\d{2},\\d{2}\",","\"storefrontId\":\"143441-19,29\","]]]]

[MITM]
hostname = %APPEND% testflight.apple.com
