#!name=迅雷
#!desc=过滤迅雷广告，解锁部分会员功能。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]
body_rewrite_18 = type=http-response, pattern=^https:\/\/conf-m-ssl\.xunlei\.com\/external\/, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["values.me_config.entrance_list_vertical_enable","values.me_config.common_service_list","values.me_config.banner_service_list"]]]

[迅雷云盘]解锁会员 = type=http-response, pattern=^https:\/\/xluser-ssl\.xunlei\.com\/xluser\.core\.login\/v3\/getuserinfo, script-path=https://raw.githubusercontent.com/Marol62926/MarScrpt/main/xunlei.js, requires-body=true

[MITM]
hostname = %APPEND% conf-m-ssl.xunlei.com, api-shoulei-ssl.xunlei.com, xluser-ssl.xunlei.com
