#!name=知识星球去水印
#!desc=移除内容的水印编号
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Script]
body_rewrite_12 = type=http-response, pattern=^https:\/\/api\.zsxq\.com\/v2\/groups\/\d+$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-replace",[["resp_data.group.policies.enable_watermark",false]]]]
body_rewrite_13 = type=http-response, pattern=^https:\/\/articles\.zsxq\.com\/inline_form\/id_[a-z0-9]+\.html, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["replace-regex",[["name=\"group_enable_watermark\" value=\"true\"","name=\"group_enable_watermark\" value=\"false\""]]]]

[MITM]
hostname = %APPEND% api.zsxq.com
