#!name=掌上无畏契约去广告
#!desc=移除开屏广告、弹窗推广、搜索热搜、搜索热榜。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/app\.mval\.qq\.com\/go\/recommend\/platflashbox\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/app\.mval\.qq\.com\/go\/mlol_news\/search\/varcache_hotV\d\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/app\.mval\.qq\.com\/go\/customize_search\/article_rank_tab\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% app.mval.qq.com
