#!name=微博轻享版
#!desc=过滤微博轻享版广告
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Map Local]
^https?:\/\/api\.weibo\.c(n|om)\/\d\/(cardlist\?v_f=\d|ad\/weibointl\?) data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https?:\/\/weibointl\.api\.weibo\.c(n|om)\/portal\.php\?a=(hot_search_users|treehole&auth=) data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/bootpreload\.uve\.weibo\.com\/v1\/ad\/preload$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.weibo\.cn\/2\/cardlist\?v_f=2 data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.weibo\.cn\/2\/ad\/ data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=get_searching_info data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_24 = type=http-response, pattern=^https:\/\/weibointl\.api\.weibo\.cn\/portal\.php\?a=trends, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.banner","data.discover","data.user_footprint","data.profile_accessrecord","data.native_content","data.topics"]]]
body_rewrite_31 = type=http-response, pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/friends\/timeline$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["advertises","ad","ad_version_2_weibo"]]]
body_rewrite_34 = type=http-response, pattern=^https:\/\/api\.weibo\.cn\/2\/statuses\/unread_hot_timeline$, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["ad","ad_version_2_weibo"]]]

[MITM]
hostname = %APPEND% bootpreload.uve.weibo.com, weibointl.api.weibo.cn, api.weibo.cn
