#!name=医考帮去广告
#!desc=移除横幅推广、弹窗、首页悬浮挂件。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Map Local]
^https:\/\/api\.yikaobang\.com\.cn\/index\.php\/client\/main\/ads\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"
^https:\/\/api\.yikaobang\.com\.cn\/index\.php\/client\/Main\/startPage\? data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[MITM]
hostname = %APPEND% api.yikaobang.com.cn
