#!name=阅友去广告
#!desc=移除开屏广告、弹窗广告和阅读页面广告，移除底栏福利按钮。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,ads.reader.yueyouxs.com,REJECT

[Script]
body_rewrite_15 = type=http-response, pattern=^https:\/\/goway\.reader\.yueyouxs\.com\/assemble\/app\/basic\/getAppInfo\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.isShowDLPopup","data.isShowGame","data.touTiaoShowDlPopup","data.offLineDownload.WatchVideoBtnDesc","data.readVipFirstCfg","data.readVipNormalCfg","data.notifyAd","data.hotStartSplashTime","data.hotStartReqSwitch","data.isShowBFTab","data.popReqDelayTime","data.benefitCfg","data.chestTask","data.hotStartAd","data.activeTagList","data.secondOrderCfg","data.secondOrderList","data.blockedWordsCfg","data.aaReportListCfg","data.pddAdSwitch","data.isShowShelfAuthPopup","data.firstPopUpAmount"]],["json-replace",[["data.isAdClosed",true]]]]

[MITM]
hostname = %APPEND% goway.reader.yueyouxs.com
