#!name=智联招聘去广告
#!desc=移除开屏广告、弹窗、职位页面推广和各类横幅推广。此插件需要IPA签名方可使用，App Store用户请勿使用此插件，务必点击下方主页链接查看详细教程。
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[Rule]
URL-REGEX,"^https:\/\/(ask|cgate)\.zhaopin\.com\/operation\/ad\/",REJECT

[URL Rewrite]
^https:\/\/cgate\.zhaopin\.com\/bdp\/commercial\/queryLinkData$ - reject

[Map Local]
^https:\/\/cgate\.zhaopin\.com\/resumeapi\/resumeCheck\/positionDetailBottomTipCheck$ data-type=text data="{}" status-code=200 header="Content-Type:application/json"

[Script]
body_rewrite_15 = type=http-response, pattern=^https:\/\/ask\.zhaopin\.com\/plat-zqa-server\/home\/\d\.\d\.\d\/getHomeContents\?, script-path=https://raw.githubusercontent.com/Script-Hub-Org/Script-Hub/main/scripts/body-rewrite.js, requires-body=true, max-size=-1, timeout=30, argument=[["json-del",["data.templates[0].data.banner"]]]

[MITM]
hostname = %APPEND% ask.zhaopin.com, cgate.zhaopin.com
