#!name =  iRingo: 📍 Location
#!desc = 自定义「定位服务」\n通过「基于网络的地区检测」结果始终为用户设置的地区。
#!icon=https://github.com/Qmxn/Tool/raw/X/icon/icon/XD.png

[Rule]
DOMAIN,gspe1-ssl.ls.apple.com,DIRECT

[Script]
📍 Location.pep.gcc.response = type=http-response, pattern=^https?:\/\/gspe1-ssl\.ls\.apple\.com\/pep\/gcc, requires-body=1, script-path=https://github.com/NSRingo/GeoServices/releases/latest/download/response.bundle.js, argument=PEP.GCC={{{GeoCountryCode}}}

[MITM]
hostname = %APPEND% gspe1-ssl.ls.apple.com
