#!name =  iRingo: ✈ TestFlight
#!desc = 1.自定义TestFlight登录商店地区\n2.多账户保存及切换(需配置BoxJs使用)\n3.让通用应用在任意苹果处理器设备上可安装
#!icon=https://github.com/Qmxn/Box/raw/X/icon/icon/XD.png

[General]
skip-proxy = %APPEND% iosapps.itunes.apple.com

[Script]
✈ TestFlight.request = type=http-request, pattern=^https?:\/\/testflight\.apple\.com\/, requires-body=1, script-path=https://github.com/NSRingo/TestFlight/releases/download/v3.4.0/request.bundle.js, argument=CountryCode="{{{CountryCode}}}"&MultiAccount="{{{MultiAccount}}}"&Universal="{{{Universal}}}"&AlwaysShowInstall="{{{AlwaysShowInstall}}}"&MergeNotifications="{{{MergeNotifications}}}"&LogLevel="{{{LogLevel}}}"
✈ TestFlight.response = type=http-response, pattern=^https?:\/\/testflight\.apple\.com\/, requires-body=1, script-path=https://github.com/NSRingo/TestFlight/releases/download/v3.4.0/response.bundle.js, argument=CountryCode="{{{CountryCode}}}"&MultiAccount="{{{MultiAccount}}}"&Universal="{{{Universal}}}"&AlwaysShowInstall="{{{AlwaysShowInstall}}}"&MergeNotifications="{{{MergeNotifications}}}"&LogLevel="{{{LogLevel}}}"

[MITM]
hostname = %APPEND% testflight.apple.com
