#!name=Spotify
#!desc=Spotify
#!icon=https://raw.githubusercontent.com/Auniquesir/Box/X/icon/Spotify.png

[Rule]
AND,((DOMAIN,spclient.wg.spotify.com),(PROTOCOL,QUIC)),REJECT
AND,((DOMAIN,gae2-spclient.spotify.com),(PROTOCOL,QUIC)),REJECT
AND,((DOMAIN,guc3-spclient.spotify.com),(PROTOCOL,QUIC)),REJECT

[URL Rewrite]
^https?:\/\/(?:gae2-spclient|guc3-spclient|spclient\.wg)\.spotify\.com(?::443)?\/pendragon\/ - reject-dict
^https?:\/\/(gae2-spclient|guc3-spclient|spclient\.wg)\.spotify\.com(?::443)?\/artistview\/v1\/artist\/(.*)&platform=iphone https://$1.spotify.com/artistview/v1/artist/$2&platform=ipad header

[Script]
Protobuf处理 = type=http-response, pattern=^https?:\/\/(?:gae2-spclient|guc3-spclient|spclient\.wg)\.spotify\.com(?::443)?\/(?:bootstrap|user-customization-service), script-path=https://kelee.one/Resource/Script/Spotify/Spotify_remove_ads.js, requires-body=true, binary-body-mode=true, timeout=5, argument="[{tab},{useractivity}]"

[MITM]
hostname = %APPEND% gae2-spclient.spotify.com, guc3-spclient.spotify.com, spclient.wg.spotify.com
