#!name=Spotify
#!desc=Spotify
#!icon=https://raw.githubusercontent.com/Auniquesir/Box/X/icon/Spotify.png


[Rule]
AND,((DOMAIN,spclient.wg.spotify.com),(PROTOCOL,QUIC)),REJECT

[URL Rewrite]
^https:\/\/spclient\.wg\.spotify\.com\/pendragon\/ - reject-dict
^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/(.*)platform=iphone https://spclient.wg.spotify.com/$1/$2platform=ipad header

[Script]
Protobuf处理 = type=http-response, pattern=^https:\/\/spclient\.wg\.spotify\.com\/(?:bootstrap|user-customization-service), script-path=https://kelee.one/Resource/Script/Spotify/Spotify_remove_ads.js, requires-body=true, binary-body-mode=true, timeout=10, argument="[{tab},{useractivity}]"

[MITM]
hostname = %APPEND% spclient.wg.spotify.com
